################################################################################
#' Process batch generic data
#'
#' @param multiassay Multiassay experiment object generated by Omix
#' `generate_multiassay`function
#' @param scale_data
#' @param remove_sample_outliers
#' @param process_func
#'
#' @return a MultiAssayExperiment object with `generic_processed` slot
#'
#' @family Pre-processing
#'
#' @importFrom MultiAssayExperiment MultiAssayExperiment listToMap colData
#' @importFrom MultiAssayExperiment getWithColData sampleMap metadata
#' @importFrom SummarizedExperiment SummarizedExperiment assay rowData
#' @importFrom cli cli_alert_danger style_bold cli_alert_success
#' @importFrom dplyr %>%
#'
#' @export

process_generic <- function(multiassay,
                        scale_data = TRUE,
                        remove_sample_outliers=FALSE,
                        process_func = function(x) return(x))  # allow the user to specify any transformation function to be applied to the data matrix (default = identity))
{

  ## get assay data
  generic_names <- grep("generic_raw", names(multiassay), value = TRUE)
  lapply(
    generic_names,
    MultiAssayExperiment::getWithColData,
    x = multiassay
  ) -> generic_assays
  lapply(
    generic_assays,
    SummarizedExperiment::colData
  ) -> colData_list
  lapply(
    generic_assays,
    function(x) SummarizedExperiment::assays(x)[[1]]
  ) -> matrix_list


  ## intilise processing
  processing_outputs <- lapply(generic_names, function(x) list())
  names(processing_outputs) <- generic_names

  ## tansformation & normalisation
  cli::cli_alert_success("SCALING & TRANSFORMATION")

  matrix_list <- lapply(matrix_list, process_func)

  mean_list <- lapply(
    matrix_list,
    function(x) {
      mean_feature <- x %>%
          rowMeans() %>%
          enframe() %>%
          as.data.frame()
      mean_sample <- x %>%
        colMeans()
      return(list(
        mean_values_feature_df = mean_feature,
        mean_values_sample = mean_sample
      ))
    }
  )

  for (i in 1:length(mean_list)) {
    processing_outputs[[i]][["raw"]] <- mean_list[[i]]
  }

  if (scale_data) {
    matrix_list <- lapply(
      matrix_list,
      function(x) t(scale(t(x)))
    )
  }

  ## outlier removal
  remove_outliers <- function(matrix) {
    dim2 <- dim(matrix)[2]
    pca <- prcomp(t(matrix), scale. = FALSE, rank. = 1)
    U <- pca$x
    outliers <- rownames(apply(
      U, 2,
      function(x) which(abs(x - mean(x)) >= (3 * sd(x)))
    ))
    matrix <- matrix[, !colnames(matrix) %in% outliers]
    cli::cli_alert_success(paste(
      length(outliers), "sample outliers out of",
      dim2, " samples detected and dropped"
    ))

    info <- list(
      sample_outliers = length(outliers),
      percentage_outliers = length(outliers)/dim2,
      detected_sample_outliers = outliers
    )
    return(list(matrix, info))

  }

  if (remove_sample_outliers) {
    cli::cli_alert_success("SAMPLE OUTLIERS REMOVAL")
    outlier_out <- lapply(matrix_list, remove_outliers)
    outlier_info <- lapply(outlier_out, function(x) x[[2]])
    matrix_list <- lapply(outlier_out, function(x) x[[1]])

    for (i in 1:length(outlier_info)) {
      processing_outputs[[i]][["remove_sample_outliers"]] <- outlier_info[[i]]
    }
  }



  ## rebuild MultiAssayExperiment
  map <- MultiAssayExperiment::sampleMap(multiassay)
  map_df <- data.frame(map@listData)

  suppressWarnings({
    for (i in 1:length(matrix_list)) {
      matrix <- matrix_list[[i]] %>% as.data.frame()
      name <- generic_names[[i]]
      assay_map <- map_df[map_df$assay == name, ]
      map <- map_df[match(
        colnames(matrix),
        map_df$colname
      ), ][c("primary", "colname")]
      new_name <- gsub('raw', 'processed', name)
      map$assay <- new_name
      multiassay <- c(multiassay,
                      setNames(list(matrix), new_name),
                      sampleMap = map)


    }

    MultiAssayExperiment::metadata(multiassay)$parameters$processing$generic <- list(
      scale_data = scale_data,
      process_func = process_func,
      remove_sample_outliers = remove_sample_outliers
    )

    MultiAssayExperiment::metadata(multiassay)$parameters$processing_outputs$generic <- processing_outputs

  })

  cli::cli_alert_success("Generic data processed!")
  cli::cli_alert_success("Processing parameters saved in metadata")

  return(multiassay)
}
