name: R GitHub Actions dev_ele_new

on:
  push:
    branches:
      - dev_ele_new

jobs:
  R-CMD-check:
    name: R-CMD-check
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RGL_USE_NULL: TRUE
    steps:
      - uses: actions/checkout@v3
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          install-r: false

      - name: Get R package version
        run: |
          version=$(grep Version DESCRIPTION | grep -o "[0-9.]\+")
          echo "packageVersion=${version}" >> $GITHUB_ENV
        shell: bash {0}
        
      - name: Create and populate .Renviron file
        run: |
          echo SYNAPSE_ID="${{ env.SYNAPSE_ID }}" >> ~/.Renviron
          echo SYNAPSE_PASSWORD="${{ env.SYNAPSE_PASSWORD }}" >> ~/.Renviron
          echo GH_TOKEN="${{ env.GH_TOKEN }}" >> ~/.Renviron
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          load: true
          file: ./Dockerfile
          tags: |
            eleonoreschneeg/omix:${{ env.packageVersion }}
            eleonoreschneeg/omix:latest
            eleonoreschneeg/omix:dev
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push service
        run: |
          docker push eleonoreschneeg/omix:${{ env.packageVersion }}
          docker push eleonoreschneeg/omix:latest
          docker push eleonoreschneeg/omix:dev
